# Generated by Django 3.0.4 on 2020-03-21 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SfeduStudent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sfedu_pass', models.CharField(max_length=50)),
                ('sfedu_username', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SfeduStuden',
        ),
    ]
