# Generated by Django 3.0.4 on 2020-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0003_auto_20200323_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sfedu_schadule',
            field=models.CharField(default='empty', max_length=5000),
        ),
    ]
