# Generated by Django 3.0.4 on 2020-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0005_auto_20200327_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_info',
            field=models.CharField(default='empty', max_length=5000),
        ),
    ]
