# Generated by Django 3.0.4 on 2020-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0007_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scoreline',
            new_name='absolute_max_scores',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_max_scores',
            field=models.CharField(default='empty', max_length=5000),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_scores',
            field=models.CharField(default='empty', max_length=5000),
        ),
    ]
