# Generated by Django 3.0.4 on 2020-03-30 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accountApp', '0008_auto_20200330_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Предмет', max_length=200)),
                ('homework_link', models.URLField(default='#', max_length=500)),
                ('aims_link', models.URLField(default='#', max_length=500)),
                ('todo_link', models.URLField(default='#', max_length=500)),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountApp.Settings')),
            ],
        ),
    ]
