# Generated by Django 3.0.4 on 2020-03-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountApp', '0009_sidebar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='settings',
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
