# Generated by Django 3.0.4 on 2020-03-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0012_auto_20200330_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.Profile'),
        ),
    ]
