# Generated by Django 3.0.4 on 2020-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0013_auto_20200330_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sfedu_username',
            field=models.CharField(default='login', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_info',
            field=models.CharField(default='Ведите учетные данные ЮФУ.', max_length=5000),
        ),
    ]
