# Generated by Django 3.0.4 on 2020-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0014_auto_20200402_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_info',
            field=models.CharField(default='Введите учетные данные ЮФУ.', max_length=5000),
        ),
    ]
