# Generated by Django 3.0.4 on 2020-03-30 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accountApp', '0006_profile_student_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url_of_notes', models.URLField(default='https://nimbusweb.me', max_length=500)),
                ('url_of_disk', models.URLField(default='https://drive.google.com/drive/my-drive', max_length=500)),
            ],
        ),
    ]
